# .goreleaser.yaml
builds:
  - binary: diskutil
    main: ./cmd/diskutil
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - binary: panago
    main: ./cmd/panago
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# Example: specify how archives (zip/tar) are produced
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .OS }}_{{ .Arch }}"
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .OS }}_{{ .Arch }}"

# Optionally define extra release notes, builds, etc.
# See https://goreleaser.com/customization/ for full config options.
