# .goreleaser.yaml
builds:
  - id: panago-cli
    binary: panago-cli
    main: ./cmd/cli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: panago
    binary: panago
    main: ./cmd/panago
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

# Example: specify how archives (zip/tar) are produced
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

# Optionally define extra release notes, builds, etc.
# See https://goreleaser.com/customization/ for full config options.
